# Generated by Django 3.1.1 on 2020-12-09 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwkTracksheetReport',
            fields=[
                ('num_houses_reached', models.IntegerField()),
                ('num_houses_doing_segg', models.IntegerField()),
                ('num_houses_giving_mixwaste', models.IntegerField()),
                ('drywaste_bf', models.IntegerField()),
                ('drywaste_af', models.IntegerField()),
                ('wetwaste_bf', models.IntegerField()),
                ('wetwaste_af', models.IntegerField()),
                ('lane_name', models.CharField(max_length=200)),
                ('num_attendants', models.IntegerField()),
                ('first_attendants_name', models.CharField(max_length=100)),
                ('second_attendants_name', models.CharField(max_length=100)),
                ('time_of_visit', models.CharField(max_length=100)),
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('supervisor_name', models.CharField(max_length=100)),
                ('num_houses', models.IntegerField(blank=True, null=True)),
                ('rejected_total', models.IntegerField(blank=True, null=True)),
                ('rejected_dry', models.IntegerField(blank=True, null=True)),
                ('rejected_wet', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'swk_tracksheet_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DutyEntry',
            fields=[
                ('lane_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('first_attendants_name', models.CharField(max_length=100)),
                ('second_attendants_name', models.CharField(max_length=100)),
                ('num_houses_lane', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Tracksheet',
            fields=[
                ('date', models.DateField()),
                ('num_houses_reached', models.IntegerField(default=20)),
                ('num_houses_doing_segg', models.IntegerField()),
                ('num_houses_giving_mixwaste', models.IntegerField()),
                ('drywaste_bf', models.IntegerField()),
                ('drywaste_af', models.IntegerField()),
                ('wetwaste_bf', models.IntegerField()),
                ('wetwaste_af', models.IntegerField()),
                ('lane_name', models.CharField(max_length=200)),
                ('num_attendants', models.IntegerField(default=2)),
                ('first_attendants_name', models.CharField(max_length=100)),
                ('second_attendants_name', models.CharField(max_length=100)),
                ('supervisor_name', models.CharField(default='Zaheer', max_length=100)),
                ('time_of_visit', models.CharField(max_length=100)),
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('rejected', models.IntegerField()),
                ('zone_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TracksheetModel',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
