# Generated by Django 3.0 on 2020-10-28 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Tracksheet',
            fields=[
                ('date', models.DateField()),
                ('num_houses_reached', models.IntegerField(default=20)),
                ('num_houses_doing_segg', models.IntegerField()),
                ('num_houses_giving_mixwaste', models.IntegerField()),
                ('drywaste_bf', models.IntegerField()),
                ('drywaste_af', models.IntegerField()),
                ('wetwaste_bf', models.IntegerField()),
                ('wetwaste_af', models.IntegerField()),
                ('lane_name', models.CharField(choices=[('Waras lane to Hira Seth chawl', 'Waras lane - Hira Seth chawl'), ('Navneet Lane to Tare Galli', 'Navneet Lane - Tare Galli'), ('BhandarWada to Amar Prem Chowk', 'BhandarWada - Amar Prem Chowk'), ('Shankar Mandir to Bhagat Galli ', 'Shankar Mandir - Bhagat Galli '), ('Gonta Galli to Kranti Galli', 'Gonta Galli - Kranti Galli'), ('Kranti Galli to Navjeevan Chauk', 'Kranti Galli - Navjeevan Chauk'), ('Pakhari Galli ', 'Pakhari Galli '), ('Vada pav Galli to Fish market', 'Vada pav Galli - Fish market'), ('Payari', 'Payari'), ('Sonapur to Dukkur Galli', 'Sonapur - Dukkur Galli'), ('Dukkur to Taak Galli', 'Dukkur - Taak Galli'), ('Nagobacha Ghumat to Achanak', 'Nagobacha Ghumat - Achanak'), ('Golfadevi', 'Golfadevi')], max_length=200)),
                ('num_attendants', models.IntegerField(default=2)),
                ('first_attendants_name', models.CharField(choices=[('Amrapali', 'Amrapali'), ('Jana pote', 'Jana pote'), ('Kaushalya', 'Kaushalya'), ('Parvati', 'Parvati'), ('Sakuntala', 'Sakuntala'), ('Asha', 'Asha')], default='Amrapali', max_length=100)),
                ('second_attendants_name', models.CharField(choices=[('Amrapali', 'Amrapali'), ('Jana pote', 'Jana pote'), ('Kaushalya', 'Kaushalya'), ('Parvati', 'Parvati'), ('Sakuntala', 'Sakuntala'), ('Asha', 'Asha')], default='Jana pote', max_length=100)),
                ('time_of_visit', models.CharField(choices=[('7:30am - 8:30 am', 'Morning'), ('7:30pm - 8:30 pm', 'Evening')], default='Morning', max_length=100)),
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TracksheetModel',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
