# Generated by Django 3.0 on 2020-10-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyEntry',
            fields=[
                ('lane_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('first_attendants_name', models.CharField(max_length=100)),
                ('second_attendants_name', models.CharField(max_length=100)),
                ('num_houses_lane', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='tracksheet',
            name='first_attendants_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tracksheet',
            name='lane_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tracksheet',
            name='second_attendants_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tracksheet',
            name='time_of_visit',
            field=models.CharField(max_length=100),
        ),
    ]
