# Generated by Django 3.0 on 2020-11-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0002_auto_20201030_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksheet',
            name='rejected',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
