# Generated by Django 3.0 on 2020-11-11 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0003_tracksheet_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracksheet',
            name='lane_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='swk.DutyEntry'),
        ),
    ]
