# Generated by Django 3.0 on 2020-11-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0004_auto_20201111_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracksheet',
            name='rejected',
        ),
        migrations.AlterField(
            model_name='tracksheet',
            name='lane_name',
            field=models.CharField(max_length=200),
        ),
    ]
