# Generated by Django 3.0 on 2020-11-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0005_auto_20201115_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracksheet',
            name='track_id',
            field=models.AutoField(default=107, primary_key=True, serialize=False),
        ),
    ]
