# Generated by Django 3.0 on 2020-11-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0006_auto_20201115_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksheet',
            name='supervior_name',
            field=models.CharField(default='Zaheer', max_length=100),
        ),
        migrations.AlterField(
            model_name='tracksheet',
            name='track_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
