# Generated by Django 3.0 on 2020-11-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0007_auto_20201119_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracksheet',
            old_name='supervior_name',
            new_name='supervisor_name',
        ),
    ]
