# Generated by Django 3.0 on 2020-11-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0008_auto_20201119_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwkTracksheetReport',
            fields=[
                ('num_houses_reached', models.IntegerField()),
                ('num_houses_doing_segg', models.IntegerField()),
                ('num_houses_giving_mixwaste', models.IntegerField()),
                ('drywaste_bf', models.IntegerField()),
                ('drywaste_af', models.IntegerField()),
                ('wetwaste_bf', models.IntegerField()),
                ('wetwaste_af', models.IntegerField()),
                ('lane_name', models.CharField(max_length=200)),
                ('num_attendants', models.IntegerField()),
                ('first_attendants_name', models.CharField(max_length=100)),
                ('second_attendants_name', models.CharField(max_length=100)),
                ('time_of_visit', models.CharField(max_length=100)),
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('supervisor_name', models.CharField(max_length=100)),
                ('num_houses', models.IntegerField(blank=True, null=True)),
                ('rejected_total', models.IntegerField(blank=True, null=True)),
                ('rejected_dry', models.IntegerField(blank=True, null=True)),
                ('rejected_wet', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'swk_tracksheet_report',
                'managed': False,
            },
        ),
    ]
