# Generated by Django 3.1.2 on 2020-11-21 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0009_swktracksheetreport'),
        ('swk', '0007_auto_20201117_0633'),
    ]

    operations = [
    ]
