# Generated by Django 3.1.1 on 2020-12-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0009_auto_20201217_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracksheet',
            old_name='zone_id',
            new_name='zone_id',
        ),
    ]
