# Generated by Django 3.1.6 on 2021-02-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0010_auto_20201217_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwkAttendants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendant1', models.CharField(blank=True, max_length=50, null=True)),
                ('attendant2', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=50, null=True)),
                ('zone_name', models.CharField(blank=True, max_length=100, null=True)),
                ('zone_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'swk_attendants',
                'managed': False,
            },
        ),
    ]
