# Generated by Django 3.1.6 on 2021-03-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0012_auto_20210302_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracksheet',
            name='num_attendants',
            field=models.CharField(default=2, max_length=100),
        ),
    ]
