# Generated by Django 3.1.6 on 2021-03-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0013_auto_20210303_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracksheet',
            name='num_attendants',
            field=models.CharField(default=2, max_length=10),
        ),
    ]
