# Generated by Django 3.1.6 on 2021-05-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0015_feedback_uploadpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('grievance', models.TextField()),
            ],
            options={
                'db_table': 'swk_grievance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('service_swk', models.IntegerField(default='yes')),
                ('timing_swk', models.IntegerField()),
                ('mobile_swk', models.IntegerField()),
                ('compost_kit_garden', models.IntegerField()),
                ('communicate_swk', models.IntegerField()),
                ('food_bin', models.CharField(default='no', max_length=10)),
                ('paper_bin', models.CharField(default='no', max_length=10)),
                ('ewaste_bin', models.CharField(default='no', max_length=10)),
                ('pads_bin', models.CharField(default='no', max_length=10)),
                ('epr_bin', models.CharField(default='no', max_length=10)),
            ],
            options={
                'db_table': 'swk_rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwkBubblePopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bubble_id', models.IntegerField(blank=True, null=True)),
                ('spot_id', models.IntegerField(blank=True, null=True)),
                ('bubble_population', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'swk_bubble_population',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UploadPicture',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.AddField(
            model_name='tracksheet',
            name='reason_late_entry',
            field=models.CharField(default='OnTime', max_length=200),
        ),
    ]
