# Generated by Django 3.1.6 on 2021-06-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0017_uploadpicturemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_names', models.CharField(blank=True, max_length=100, null=True)),
                ('supervisor_email', models.CharField(blank=True, max_length=100, null=True)),
                ('zone_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'swk_zone_supervisors',
                'managed': False,
            },
        ),
    ]
