# Generated by Django 3.1.6 on 2021-10-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swk', '0019_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksheet',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
